### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by Dhruv-1608** [Narmis-E/hyprland-dots#1]
Hi there, I really enjoy your rice and thought the final product was quite amazing. Additionally, I wanted to test it out on my own device, but I'm running into a few problems. Please share your Discord username or any other social media handle so that we may continue our conversation about this matter. I'd also like to talk about a few other subjects. Since this was my only means of getting in touch with you, I am opening this issue to let you know.

**Comment by Narmis-E** [comment]
Hey, I'd be glad to help! I didn't really expect anyone to use this as I've marked it as deprecated 😅
I think my discord username should just be `narmis`?
Thank you!

**Comment by Dhruv-1608** [comment]
I have sent you the friend request over Discord and thank you very much for replying quickly. You can close the following issue, and we can further discuss over Discord.
Thank you once again :>
